import gradio as gr
import os
import json
import shutil
from processor import extract_text, segment_into_clauses, process_multilingual_clause
from legal_engine import get_risk_assessment, calculate_overall_risk, classify_contract, generate_executive_summary, get_chat_response
from utils import generate_pdf_report

# --- WRAPPER FOR GRADIO FILES ---
def process_file_wrapper(file_obj):
    """Gradio passes a file path. We need to open it for your existing functions."""
    if file_obj is None:
        return "Please upload a file.", None, None, None

    # Determine extension
    file_path = file_obj.name
    file_ext = os.path.splitext(file_path)[1].lower()
    
    # Read file based on type
    if file_ext == ".pdf":
        mode = "rb"
    else:
        mode = "rb" # python-docx also needs binary
        
    with open(file_path, mode) as f:
        raw_text = extract_text(f, file_ext)

    # 1. Classify
    doc_type = classify_contract(raw_text)
    
    # 2. Segment & Analyze
    clauses = segment_into_clauses(raw_text)
    results = []
    
    # Analyze (limit to first 10 clauses for speed in demo)
    for c in clauses:
        clean_text, _ = process_multilingual_clause(c['content'])
        analysis = get_risk_assessment(clean_text)
        results.append({
            "header": c['header'], 
            "analysis": analysis, 
            "original": c['content']
        })

    # 3. Score & Report
    risk_score = calculate_overall_risk(results)
    summary = generate_executive_summary(raw_text)
    
    # 4. Generate Files
    # JSON Log
    log_data = {
        "doc_type": doc_type,
        "risk_score": risk_score,
        "analysis": results
    }
    json_path = "audit_log.json"
    with open(json_path, "w") as f:
        json.dump(log_data, f, indent=4)
        
    # PDF Report
    pdf_bytes = generate_pdf_report(doc_type, summary, results, risk_score)
    pdf_path = "NyayaSetu_Report.pdf"
    with open(pdf_path, "wb") as f:
        f.write(pdf_bytes)

    # 5. Create HTML Output for UI
    html_output = f"""
    <div style="text-align: center;">
        <h1 style="color: {'#ff4b4b' if risk_score > 70 else '#ffa421'}; font-size: 40px;">
            Risk Score: {risk_score}/100
        </h1>
        <h3>Type: {doc_type}</h3>
    </div>
    <hr>
    """
    
    for r in results:
        lbl = r['analysis'].get('label', 'Low')
        color = "#ff4b4b" if lbl == "High" else "#ffa421" if lbl == "Medium" else "#09ab3b"
        
        if lbl != "Low": # Show only critical findings in UI to keep it clean
            html_output += f"""
            <div style="border-left: 5px solid {color}; padding: 10px; margin-bottom: 10px; background-color: #f9f9f9;">
                <b style="color: {color};">[{lbl.upper()}] {r['header']}</b><br>
                <i>{r['analysis']['explanation']}</i><br>
                <b>Better:</b> {r['analysis']['alternative_clause']}
            </div>
            """

    return html_output, json_path, pdf_path, raw_text # Return text for chatbot

# --- CHAT WRAPPER ---
def chat_wrapper(message, history, context):
    if not context:
        return "Please upload and analyze a contract first."
    return get_chat_response(context, message)

# --- TEMPLATE WRAPPER ---
def template_wrapper(template_type):
    content = f"STANDARD {template_type.upper()} TEMPLATE\n\n(Generated by NyayaSetu)\n\n1. DEFINITIONS..."
    path = f"{template_type.replace(' ', '_')}.txt"
    with open(path, "w") as f:
        f.write(content)
    return path

# --- UI LAYOUT ---
with gr.Blocks(title="NyayaSetu Legal AI", theme=gr.themes.Soft()) as demo:
    
    # Store contract text for chat context
    contract_state = gr.State()

    gr.Markdown("# ⚖️ NyayaSetu: AI Legal Auditor")
    
    with gr.Tab("🚀 Risk Audit"):
        with gr.Row():
            file_input = gr.File(label="Upload Contract (PDF/DOCX)", file_types=[".pdf", ".docx", ".txt"])
            btn_analyze = gr.Button("⚡ Run Deep Analysis", variant="primary")
        
        with gr.Row():
            report_view = gr.HTML(label="Analysis Report")
        
        with gr.Row():
            dl_json = gr.File(label="Download JSON Log")
            dl_pdf = gr.File(label="Download PDF Report")

        # Link functions
        btn_analyze.click(
            process_file_wrapper, 
            inputs=[file_input], 
            outputs=[report_view, dl_json, dl_pdf, contract_state]
        )

    with gr.Tab("💬 Legal Assistant"):
        chatbot = gr.ChatInterface(
            fn=chat_wrapper,
            additional_inputs=[contract_state],
            title="Ask questions about your contract"
        )

    with gr.Tab("📝 Templates"):
        dropdown = gr.Dropdown(["Employment Agreement", "NDA", "Service Contract"], label="Choose Template")
        btn_temp = gr.Button("Generate")
        file_temp = gr.File(label="Download Template")
        
        btn_temp.click(template_wrapper, inputs=[dropdown], outputs=[file_temp])

# Run it
if __name__ == "__main__":
    demo.launch()